/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   syscall_names_64.h                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: avasseur <avasseur@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2016/04/17 22:49:24 by avasseur          #+#    #+#             */
/*   Updated: 2016/06/09 06:08:42 by flo              ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef SYSCALL_NAMES_64_H
# define SYSCALL_NAMES_64_H

static const char     syscall_names_64[320][10][50] =
{
    { "read", "uint", "3", "int", "str", "uint"},
    { "write", "uint", "3", "int", "str", "uint"},
    { "open", "int", "3", "str", "int", "uint"},
    { "close", "long", "1", "uint"},
    { "stat", "int", "2", "str", "ptr"},
    { "fstat", "int", "2", "uint", "ptr"},
    { "lstat", "int", "2", "str", "ptr"},
    { "poll", "int", "3", "ptr", "uint", "int"},
    { "lseek", "long", "3", "uint", "long", "uint"},
    { "mmap", "ptr", "6", "ptr", "uint", "int", "int", "int", "uint"},
    { "mprotect", "int", "3", "ptr", "ulong", "ulong"},
    { "munmap", "int", "2", "ptr", "ulong"},
    { "brk", "ptr", "1", "ptr"},
    { "rt_sigaction", "long", "4", "int", "ptr", "ptr", "uint"},
    { "rt_sigprocmask", "long", "4", "int", "ptr", "ptr", "uint"},
    { "rt_sigreturn", "long", "0" },
    { "ioctl", "int", "3", "uint", "uint", "ulong"},
    { "pread64", "long", "4", "uint", "str", "ulong", "long"},
    { "pwrite64", "long", "4", "uint", "str", "ulong", "long"},
    { "readv", "long", "3", "ulong", "ptr", "ulong"},
    { "writev", "long", "3", "ulong", "ptr", "ulong"},
    { "access", "int", "2", "str", "int"},
    { "pipe", "int", "1", "ptr"},
    { "select", "int", "5", "int", "ptr", "ptr", "ptr", "ptr"},
    { "sched_yield", "long", "0" },
    { "mremap", "ptr", "1", "ulong"},
    { "msync", "int", "3", "ulong", "ulong", "int"},
    { "mincore", "int", "3", "ulong", "ulong", "str"},
    { "madvise", "long", "3", "ulong", "ulong", "int"},
    { "shmget", "int", "3", "int", "ulong", "int"},
    { "shmat", "ptr", "3", "int", "str", "int"},
    { "shmctl", "int", "3", "int", "int", "ptr"},
    { "dup", "int", "1", "uint"},
    { "dup2", "int", "2", "uint", "uint"},
    { "pause", "long", "0" },
    { "nanosleep", "int", "2", "ptr", "ptr"},
    { "getitimer", "int", "2", "int", "ptr"},
    { "alarm", "uint", "1", "uint"},
    { "setitimer", "int", "3", "int", "ptr", "ptr"},
    { "getpid", "long", "0" },
    { "sendfile", "long", "4", "int", "int", "ptr", "uint"},
    { "socket", "int", "3", "int", "int", "int"},
    { "connect", "int", "3", "int", "ptr", "int"},
    { "accept", "int", "3", "int", "ptr", "ptr"},
    { "sendto", "long", "6", "int", "ptr", "ulong", "uint", "ptr", "int"},
    { "recvfrom", "long", "6", "int", "ptr", "ulong", "uint", "ptr", "ptr"},
    { "sendmsg", "long", "3", "int", "ptr", "uint"},
    { "recvmsg", "long", "3", "int", "ptr", "uint"},
    { "shutdown", "int", "2", "int", "int"},
    { "bind", "int", "3", "int", "ptr", "int"},
    { "listen", "int", "2", "int", "int"},
    { "getsockname", "int", "3", "int", "ptr", "ptr"},
    { "getpeername", "int", "3", "int", "ptr", "ptr"},
    { "socketpair", "int", "4", "int", "int", "int", "ptr"},
    { "setsockopt", "int", "5", "int", "int", "int", "str", "int"},
    { "getsockopt", "int", "5", "int", "int", "int", "str", "ptr"},
    { "clone", "long", "5", "ulong", "ptr", "ptr", "ptr", "ptr"},
    { "fork", "long", "0" },
    { "vfork", "long", "0" },
    { "execve", "int", "3", "str", "array", "array"},
    { "exit", "long", "1", "int"},
    { "wait4", "int", "4", "int", "ptr", "int", "ptr"},
    { "kill", "int", "2", "int", "int"},
    { "uname", "int", "1", "ptr"},
    { "semget", "int", "3", "int", "int", "int"},
    { "semop", "int", "3", "int", "ptr", "uint"},
    { "semctl", "int", "4", "int", "int", "int", "ulong"},
    { "shmdt", "int", "1", "str"},
    { "msgget", "int", "2", "int", "int"},
    { "msgsnd", "int", "4", "int", "ptr", "ulong", "int"},
    { "msgrcv", "long", "5", "int", "ptr", "ulong", "long", "int"},
    { "msgctl", "int", "3", "int", "int", "ptr"},
    { "fcntl", "int", "3", "uint", "uint", "ulong"},
    { "flock", "int", "2", "uint", "uint"},
    { "fsync", "int", "1", "uint"},
    { "fdatasync", "int", "1", "uint"},
    { "truncate", "int", "2", "str", "long"},
    { "ftruncate", "int", "2", "uint", "ulong"},
    { "getdents", "int", "3", "uint", "ptr", "uint"},
    { "getcwd", "long", "2", "str", "ulong"},
    { "chdir", "int", "1", "str"},
    { "fchdir", "int", "1", "uint"},
    { "rename", "int", "2", "str", "str"},
    { "mkdir", "int", "2", "str", "uint"},
    { "rmdir", "int", "1", "str"},
    { "creat", "int", "2", "str", "uint"},
    { "link", "int", "2", "str", "str"},
    { "unlink", "int", "1", "str"},
    { "symlink", "int", "2", "str", "str"},
    { "readlink", "long", "3", "str", "str", "int"},
    { "chmod", "int", "2", "str", "uint"},
    { "fchmod", "int", "2", "uint", "uint"},
    { "chown", "int", "3", "str", "uint", "uint"},
    { "fchown", "int", "3", "uint", "uint", "uint"},
    { "lchown", "int", "3", "str", "uint", "uint"},
    { "umask", "long", "1", "int"},
    { "gettimeofday", "int", "2", "ptr", "ptr"},
    { "getrlimit", "long", "2", "uint", "ptr"},
    { "getrusage", "int", "2", "int", "ptr"},
    { "sysinfo", "long", "1", "ptr"},
    { "times", "ulong", "1", "ptr"},
    { "ptrace", "long", "4", "long", "long", "ptr", "ptr"},
    { "getuid", "long", "0" },
    { "syslog", "int", "3", "int", "str", "int"},
    { "getgid", "long", "0" },
    { "setuid", "int", "1", "uint"},
    { "setgid", "int", "1", "uint"},
    { "geteuid", "long", "0" },
    { "getegid", "long", "0" },
    { "setpgid", "int", "2", "int", "int"},
    { "getppid", "long", "0" },
    { "getpgrp", "int", "0" },
    { "setsid", "long", "0" },
    { "setreuid", "int", "2", "uint", "uint"},
    { "setregid", "int", "2", "uint", "uint"},
    { "getgroups", "int", "2", "int", "ptr"},
    { "setgroups", "int", "2", "int", "ptr"},
    { "setresuid", "int", "3", "uint", "uint", "uint"},
    { "getresuid", "int", "3", "ptr", "ptr", "ptr"},
    { "setresgid", "int", "3", "uint", "uint", "uint"},
    { "getresgid", "int", "3", "ptr", "ptr", "ptr"},
    { "getpgid", "int", "1", "int"},
    { "setfsuid", "int", "1", "uint"},
    { "setfsgid", "int", "1", "uint"},
    { "getsid", "int", "1", "int"},
    { "capget", "int", "2", "ptr", "ptr"},
    { "capset", "int", "2", "ptr", "ptr"},
    { "rt_sigpending", "long", "2", "ptr", "ulong"},
    { "rt_sigtimedwait", "long", "4", "ptr", "ptr", "ptr", "ulong"},
    { "rt_sigqueueinfo", "int", "3", "int", "int", "ptr"},
    { "rt_sigsuspend", "long", "2", "ptr", "ulong"},
    { "sigaltstack", "int", "2", "ptr", "ptr"},
    { "utime", "int", "2", "str", "ptr"},
    { "mknod", "int", "3", "str", "uint", "uint"},
    { "uselib", "int", "1", "str"},
    { "personality", "int", "1", "uint"},
    { "ustat", "int", "2", "uint", "ptr"},
    { "statfs", "int", "2", "str", "ptr"},
    { "fstatfs", "int", "2", "uint", "ptr"},
    { "sysfs", "int", "3", "int", "ulong", "ulong"},
    { "getpriority", "int", "2", "int", "int"},
    { "setpriority", "int", "3", "int", "int", "int"},
    { "sched_setparam", "int", "2", "int", "ptr"},
    { "sched_getparam", "int", "2", "int", "ptr"},
    { "sched_setscheduler", "int", "3", "int", "int", "ptr"},
    { "sched_getscheduler", "int", "1", "int"},
    { "sched_get_priority_max", "int", "1", "int"},
    { "sched_get_priority_min", "int", "1", "int"},
    { "sched_rr_get_interval", "int", "2", "int", "ptr"},
    { "mlock", "int", "2", "ulong", "ulong"},
    { "munlock", "int", "2", "ulong", "ulong"},
    { "mlockall", "int", "1", "int"},
    { "munlockall", "long", "0" },
    { "vhangup", "long", "0" },
    { "modify_ldt", "int", "3", "int", "ptr", "ulong"},
    { "pivot_root", "int", "2", "str", "str"},
    { "_sysctl", "int", "1", "ptr"},
    { "prctl", "int", "5", "int", "ulong", "ulong", "ulong", "ulong"},
    { "arch_prctl", "int", "2", "int", "ptr"},
    { "adjtimex", "int", "1", "ptr"},
    { "setrlimit", "long", "2", "uint", "ptr"},
    { "chroot", "int", "1", "str"},
    { "sync", "long", "0" },
    { "acct", "int", "1", "str"},
    { "settimeofday", "int", "2", "ptr", "ptr"},
    { "mount", "int", "5", "str", "str", "str", "ulong", "ptr"},
    { "umount2", "int", "2", "str", "int"},
    { "swapon", "int", "2", "str", "int"},
    { "swapoff", "int", "1", "str"},
    { "reboot", "int", "4", "int", "int", "uint", "ptr"},
    { "sethostname", "int", "2", "str", "int"},
    { "setdomainname", "long", "2", "str", "int"},
    { "iopl", "int", "1", "uint"},
    { "ioperm", "int", "3", "ulong", "ulong", "int"},
    { "create_module", "ulong", "0" },
    { "init_module", "int", "3", "ptr", "ulong", "str"},
    { "delete_module", "int", "2", "str", "uint"},
    { "get_kernel_syms", "int", "0" },
    { "query_module", "long", "0" },
    { "quotactl", "int", "4", "uint", "str", "uint", "ptr"},
    { "nfsservctl", "long", "0" },
    { "getpmsg", "long", "0" },
    { "putpmsg", "long", "0" },
    { "afs_syscall", "long", "0" },
    { "tuxcall", "long", "0" },
    { "security", "long", "0" },
    { "gettid", "long", "0" },
    { "readahead", "long", "3", "int", "long", "ulong"},
    { "setxattr", "long", "5", "str", "str", "ptr", "ulong", "int"},
    { "lsetxattr", "long", "5", "str", "str", "ptr", "ulong", "int"},
    { "fsetxattr", "long", "5", "int", "str", "ptr", "ulong", "int"},
    { "getxattr", "long", "4", "str", "str", "ptr", "ulong"},
    { "lgetxattr", "long", "4", "str", "str", "ptr", "ulong"},
    { "fgetxattr", "long", "4", "int", "str", "ptr", "ulong"},
    { "listxattr", "long", "3", "str", "str", "ulong"},
    { "llistxattr", "long", "3", "str", "str", "ulong"},
    { "flistxattr", "long", "3", "int", "str", "ulong"},
    { "removexattr", "long", "2", "str", "str"},
    { "lremovexattr", "long", "2", "str", "str"},
    { "fremovexattr", "long", "2", "int", "str"},
    { "tkill", "int", "2", "int", "int"},
    { "time", "ulong", "1", "ptr"},
    { "futex", "int", "6", "ptr", "int", "uint", "ptr", "ptr", "uint"},
    { "sched_setaffinity", "int", "3", "int", "uint", "ptr"},
    { "sched_getaffinity", "int", "3", "int", "uint", "ptr"},
    { "set_thread_area", "int", "1", "ptr"},
    { "io_setup", "int", "2", "uint", "ptr"},
    { "io_destroy", "int", "1", "ulong"},
    { "io_getevents", "int", "5", "ulong", "long", "long", "ptr", "ptr"},
    { "io_submit", "int", "3", "ulong", "long", "ptr"},
    { "io_cancel", "int", "3", "ulong", "ptr", "ptr"},
    { "get_thread_area", "int", "1", "ptr"},
    { "lookup_dcookie", "int", "3", "ulong", "str", "ulong"},
    { "epoll_create", "int", "1", "int"},
    { "epoll_ctl_old", "long", "0" },
    { "epoll_wait_old", "long", "0" },
    { "remap_file_pages", "int", "5", "ulong", "ulong", "ulong", "ulong", "ulong"},
    { "getdents64", "long", "3", "uint", "ptr", "uint"},
    { "set_tid_address", "long", "1", "ptr"},
    { "restart_syscall", "long", "0" },
    { "semtimedop", "int", "4", "int", "ptr", "uint", "ptr"},
    { "fadvise64", "long", "4", "int", "long", "ulong", "int"},
    { "timer_create", "int", "3", "int", "ptr", "ptr"},
    { "timer_settime", "int", "4", "ulong", "int", "ptr", "ptr"},
    { "timer_gettime", "int", "2", "ulong", "ptr"},
    { "timer_getoverrun", "int", "1", "ulong"},
    { "timer_delete", "int", "1", "ulong"},
    { "clock_settime", "int", "2", "int", "ptr"},
    { "clock_gettime", "int", "2", "int", "ptr"},
    { "clock_getres", "int", "2", "int", "ptr"},
    { "clock_nanosleep", "int", "4", "int", "int", "ptr", "ptr"},
    { "exit_group", "long", "1", "int"},
    { "epoll_wait", "int", "4", "int", "ptr", "int", "int"},
    { "epoll_ctl", "int", "4", "int", "int", "int", "ptr"},
    { "tgkill", "int", "3", "int", "int", "int"},
    { "utimes", "int", "2", "str", "ptr"},
    { "vserver", "long", "0" },
    { "mbind", "int", "6", "ulong", "ulong", "ulong", "ptr", "ulong", "uint"},
    { "set_mempolicy", "long", "3", "int", "ptr", "ulong"},
    { "get_mempolicy", "int", "5", "ptr", "ptr", "ulong", "ulong", "ulong"},
    { "mq_open", "long", "4", "str", "int", "uint", "ptr"},
    { "mq_unlink", "long", "1", "str"},
    { "mq_timedsend", "long", "5", "ulong", "str", "ulong", "uint", "ptr"},
    { "mq_timedreceive", "long", "5", "ulong", "str", "ulong", "ptr", "ptr"},
    { "mq_notify", "long", "2", "ulong", "ptr"},
    { "mq_getsetattr", "int", "3", "ulong", "ptr", "ptr"},
    { "kexec_load", "long", "4", "ulong", "ulong", "ptr", "ulong"},
    { "waitid", "int", "5", "int", "int", "ptr", "int", "ptr"},
    { "add_key", "int", "5", "str", "str", "ptr", "ulong", "int"},
    { "request_key", "int", "4", "str", "str", "str", "int"},
    { "keyctl", "long", "5", "int", "ulong", "ulong", "ulong", "ulong"},
    { "ioprio_set", "int", "3", "int", "int", "int"},
    { "ioprio_get", "int", "2", "int", "int"},
    { "inotify_init", "long", "0" },
    { "inotify_add_watch", "int", "3", "int", "str", "uint"},
    { "inotify_rm_watch", "int", "2", "int", "int"},
    { "migrate_pages", "long", "4", "int", "ulong", "ptr", "ptr"},
    { "openat", "int", "4", "int", "str", "int", "uint"},
    { "mkdirat", "int", "3", "int", "str", "uint"},
    { "mknodat", "int", "4", "int", "str", "uint", "uint"},
    { "fchownat", "int", "5", "int", "str", "uint", "uint", "int"},
    { "futimesat", "int", "3", "int", "str", "ptr"},
    { "newfstatat", "long", "4", "int", "str", "ptr", "int"},
    { "unlinkat", "int", "3", "int", "str", "int"},
    { "renameat", "int", "4", "int", "str", "int", "str"},
    { "linkat", "int", "5", "int", "str", "int", "str", "int"},
    { "symlinkat", "int", "3", "str", "int", "str"},
    { "readlinkat", "int", "4", "int", "str", "str", "int"},
    { "fchmodat", "int", "3", "int", "str", "uint"},
    { "faccessat", "int", "3", "int", "str", "int"},
    { "pselect6", "long", "6", "int", "ptr", "ptr", "ptr", "ptr", "ptr"},
    { "ppoll", "int", "5", "ptr", "uint", "ptr", "ptr", "ulong"},
    { "unshare", "int", "1", "ulong"},
    { "set_robust_list", "long", "2", "ptr", "ulong"},
    { "get_robust_list", "long", "3", "int", "ptr", "ptr"},
    { "splice", "long", "6", "int", "ptr", "int", "ptr", "ulong", "uint"},
    { "tee", "long", "4", "int", "int", "ulong", "uint"},
    { "sync_file_range", "int", "4", "int", "long", "long", "uint"},
    { "vmsplice", "long", "4", "int", "ptr", "ulong", "uint"},
    { "move_pages", "long", "6", "int", "ulong", "ptr", "ptr", "ptr", "int"},
    { "utimensat", "int", "4", "int", "str", "ptr", "int"},
    { "epoll_pwait", "int", "6", "int", "ptr", "int", "int", "ptr", "ulong"},
    { "signalfd", "int", "3", "int", "ptr", "ulong"},
    { "timerfd_create", "int", "2", "int", "int"},
    { "eventfd", "int", "1", "uint"},
    { "fallocate", "int", "4", "int", "int", "long", "long"},
    { "timerfd_settime", "int", "4", "int", "int", "ptr", "ptr"},
    { "timerfd_gettime", "int", "2", "int", "ptr"},
    { "accept4", "int", "4", "int", "ptr", "ptr", "int"},
    { "signalfd4", "long", "4", "int", "ptr", "ulong", "int"},
    { "eventfd2", "long", "2", "uint", "int"},
    { "epoll_create1", "int", "1", "int"},
    { "dup3", "int", "3", "uint", "uint", "int"},
    { "pipe2", "int", "2", "ptr", "int"},
    { "inotify_init1", "int", "1", "int"},
    { "preadv", "long", "5", "ulong", "ptr", "ulong", "ulong", "ulong"},
    { "pwritev", "long", "5", "ulong", "ptr", "ulong", "ulong", "ulong"},
    { "rt_tgsigqueueinfo", "int", "4", "int", "int", "int", "ptr"},
    { "perf_event_open", "int", "5", "ptr", "int", "int", "int", "ulong"},
    { "recvmmsg", "int", "5", "int", "ptr", "uint", "uint", "ptr"},
    { "fanotify_init", "long", "2", "uint", "uint"},
    { "fanotify_mark", "long", "5", "int", "uint", "ulong", "int", "str"},
    { "prlimit64", "long", "4", "int", "uint", "ptr", "ptr"},
    { "name_to_handle_at", "long", "5", "int", "str", "ptr", "ptr", "int"},
    { "open_by_handle_at", "long", "3", "int", "ptr", "int"},
    { "clock_adjtime", "long", "2", "int", "ptr"},
    { "syncfs", "int", "1", "int"},
    { "sendmmsg", "int", "4", "int", "ptr", "uint", "uint"},
    { "setns", "int", "2", "int", "int"},
    { "getcpu", "int", "3", "ptr", "ptr", "ptr"},
    { "process_vm_readv", "long", "6", "int", "ptr", "ulong", "ptr", "ulong", "ulong"},
    { "process_vm_writev", "long", "6", "int", "ptr", "ulong", "ptr", "ulong", "ulong"},
    { "kcmp", "int", "5", "int", "int", "int", "ulong", "ulong"},
    { "finit_module", "int", "3", "int", "str", "int"},
};

#endif
